### ISSUE TITLE
Failed to update param 68. getParameterData() failed. Received bad start byte. Received: 0a

### ISSUE THREAD

**Issue by bgilreath** [RoverRobotics/rr_openrover_stack#49]
Running example.launch on ROS Melodic. Raspberry Pi 3B+, 

` roslaunch rr_openrover_driver example.launch 
... logging to /home/ubuntu/.ros/log/40700756-8814-11ea-b8ad-b827eb2b8561/roslaunch-rover0.local-11165.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://rover0.local:46653/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.5
 * /rr_openrover_driver/closed_loop_control_on: False
 * /rr_openrover_driver/drive_type: 2wd
 * /rr_openrover_driver/enable_timeout: True
 * /rr_openrover_driver/fast_data_rate: 10.0
 * /rr_openrover_driver/medium_data_rate: 2.0
 * /rr_openrover_driver/odom_covariance_0: 0.01
 * /rr_openrover_driver/odom_covariance_35: 0.03
 * /rr_openrover_driver/port: /dev/rover-zero
 * /rr_openrover_driver/slow_data_rate: 1.0
 * /rr_openrover_driver/timeout: 0.3
 * /rr_openrover_driver/total_weight: 20.41
 * /rr_openrover_driver/traction_factor: 0.61
 * /rr_openrover_driver/use_legacy: False

NODES
  /
    rr_openrover_diagnostics_node (rr_openrover_driver/diagnostics.py)
    rr_openrover_driver (rr_openrover_driver/openrover_driver_node)

auto-starting new master
process[master]: started with pid [11190]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 40700756-8814-11ea-b8ad-b827eb2b8561
process[rosout-1]: started with pid [11234]
started core service [/rosout]
process[rr_openrover_driver-2]: started with pid [11239]
process[rr_openrover_diagnostics_node-3]: started with pid [11242]
[ INFO] [1587943118.993086574]: odom Kp: 0.000000
[ INFO] [1587943118.997842108]: odom Ki: 0.000000
[ INFO] [1587943118.998398770]: odom Kd: 0.000000
[ INFO] [1587943118.998531686]: odom Kp: 0.000000
[ INFO] [1587943118.998596268]: odom Ki: 0.000000
[ INFO] [1587943118.998657101]: odom Kd: 0.000000
[ INFO] [1587943118.998775173]: Initializing openrover driver.
[ INFO] [1587943119.000898177]: Opening serial port
[ INFO] [1587943119.003146908]: Serial port opened
[ WARN] [1587943119.019436983]: Failed to retrieve Kp from parameter.Defaulting to 40.000000
[ WARN] [1587943119.022117794]: Failed to retrieve Ki from parameter.Defaulting to 100.000000
[ WARN] [1587943119.031418603]: Failed to retrieve Kd from parameter.Defaulting to 0.000000
[ INFO] [1587943119.037034286]: Not logging left motor PID
[ INFO] [1587943119.039936970]: Not logging right motor PID
[ INFO] [1587943119.040121604]: 2wd parameters loaded.
[ INFO] [1587943119.045954525]: Openrover parameters loaded:
[ INFO] [1587943119.046146346]: port: /dev/rover-zero
[ INFO] [1587943119.046223794]: drive_type: 2wd
[ INFO] [1587943119.046301189]: timeout: 0.300000 s
[ INFO] [1587943119.046370355]: closed_loop_control_on: 0
[ INFO] [1587943119.046441656]: total_weight: 20.410000 kg
[ INFO] [1587943119.046510666]: traction_factor: 0.610000
[ INFO] [1587943119.046579260]: odom_covariance_0: 0.010000
[ INFO] [1587943119.046648321]: odom_covariance_35: 0.030000
[ INFO] [1587943119.046742175]: fast_data_rate: 10.000000 hz
[ INFO] [1587943119.046810039]: medium_data_rate: 2.000000 hz
[ INFO] [1587943119.046879205]: slow_data_rate: 1.000000 hz
[ INFO] [1587943119.046951288]: 40.000000, 100.000000, 0.000000
[ INFO] [1587943119.047051026]: Creating Publishers and Subscribers
[ERROR] [1587943119.670075959]: Failed to update param 30. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943120.189923927]: Failed to update param 28. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943120.709847363]: Failed to update param 70. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943121.229861164]: Failed to update param 68. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943121.749871527]: Failed to update param 46. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943122.270072045]: Failed to update param 44. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943122.789984962]: Failed to update param 42. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943123.309805953]: Failed to update param 38. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943123.829978504]: Failed to update param 12. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943124.349901943]: Failed to update param 10. getParameterData() failed. Received bad start byte. Received: 0a
[ERROR] [1587943124.869892048]: Failed to update param 8. getParameterData() failed. Received bad start byte. Received: 0a
[ WARN] [1587943124.870458345]: Fast data rate too high. Consider reducing fast_data_rate para`

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by padiln** [comment]
Based on the naming of the device port it looks like you are using the Rover Zero.  If that is the case then you will want to use rr_rover_zero_driver rather than rr_openrover_driver. You will want to launch using 
`roslaunch rr_rover_zero_driver example.launch`.  This just launches the driver.

Here is a tutorial on our website to setup the rover-zero: [Tutorial](https://roverrobotics.com/pages/rover-zero-tutorial-2)

**Comment by bgilreath** [comment]
Thanks! That was the issue.
