### ISSUE TITLE
Diagnostics topic throwing error from firmware message

### ISSUE THREAD

**Issue by bgilreath** [RoverRobotics/rr_openrover_stack#52]
Line 109, in rover_zero.py:
`DiagnosticStatus(name='Firmware Version', message=self._firmware_version),`
is preventing /diagnostics topic from returning rover zero info due to _firmware_version returning an array, not a single value.

Line 53, is root cause:
`self._firmware_version =self._roboclaw.ReadVersion(self._address)` as roboclaw returns array.

What direction to apply fix?
1. self._roboclaw.ReadVersion(self._address)[1] for line 53
2. self._firmware_version[1] on line 109 or message=str(self._firmware_version)

**Comment by padiln** [comment]
Merged as of [PR 56](https://github.com/RoverRobotics/rr_openrover_stack/pull/56)
